SCTF/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from rest_framework import routers
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^challenges/', include('challenges.urls')),

    url(r'^admin/game_start/', views.game_play, name='admin_game_start'),
    url(r'^admin/game_pause/', views.game_pause, name='admin_game_pause'),
    url(r'^admin/game_setup/', views.game_reset, name='admin_game_setup'),
    url(r'^admin/game_reset_users/', views.game_reset_users, name='admin_game_reset_users'),

    url(r'^game_paused/$', views.game_paused_view, name='game_paused_view'),
    url(r'^game_stopped/$', views.game_stopped_view, name='game_stopped_view'),
    url(r'^game_setup/$', views.game_setup_state_view, name='game_setup_state_view'),

    url(r'^admin/game_end/', views.game_end, name='admin_game_end'),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^tinymce/', include('tinymce.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

router = routers.SimpleRouter()

# Include REST
urlpatterns.append(url(r'^api/', include(router.urls)))

urlpatterns.append(url(r'^api/challenges/',
                       include('challenges.api_urls', namespace='api_challenge')))


urlpatterns.append(url(r'^api/users/',
                       include('accounts.api_urls', namespace='api_users')))

accounts/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from accounts.views import CustomRegistrationView
from . import views

urlpatterns = [
    url(r'^registration/register/$',
        CustomRegistrationView.as_view(),
        name='registration_register'
    ),

    url(r'^registration/', include('django_registration.backends.one_step.urls')),
    url(r'^registration/', include('django.contrib.auth.urls')),
    url(r'^teams/$', views.index, name='teams'),
    url(r'^team/$', views.team_detail, name='team'),
    url(r'^team/(?P<pk>\w+)$', views.team_detail, name='team'),
    url(r'^user/$', views.user_detail, name='user'),
    url(r'^user/(?P<pk>\w+)$', views.user_detail, name='user'),
    url(r'^user/update/$', views.UserProfileUpdateView.as_view(), name='user_update'),

    url(r'^no-team/$', views.no_team_view, name='no_team'),

    url(r'^team/admin/$', views.TeamAdminView.as_view(), name='team_admin'),

    url(r'^team/create/$', views.TeamCreateView.as_view(), name='user_team_create'),

    url(r'^team/request/create/$',
        views.UserTeamRequestCreate.as_view(), name='user_team_request_create'),

    url(r'^team/request/delete/(?P<pk>\w+)/$',
        views.UserTeamRequestDelete.as_view(), name='user_team_request_delete'),

    url(r'^team/admin/request/(?P<pk>\w+)/$',
        views.UserTeamRequestManage.as_view(), name='user_team_request_manage'),

    url(r'^no-profile/$',
        TemplateView.as_view(template_name="accounts/no_profile.html"),
        name='no_profile'
    ),

]

accounts/forms.py
from django import forms
from django.forms.models import ModelForm
# from registration.forms import RegistrationForm
from django_registration.forms import RegistrationForm
from accounts.models import UserProfile, UserTeamRequest, Team


class CustomRegistrationForm(RegistrationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = RegistrationForm.Meta.model
        fields = RegistrationForm.Meta.fields + ['first_name', 'last_name']


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['user', 'team']


class TeamCreateForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name']


class UserTeamRequestCreateForm(ModelForm):
    class Meta:
        model = UserTeamRequest
        fields = ['user', 'team']

accounts/views.py
import json
from builtins import super

from django.http import HttpResponseForbidden
from django.urls.base import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
# from registration.backends.simple.views import RegistrationView
from django_registration.views import RegistrationView
from rest_framework.response import Response
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from rest_framework.viewsets import ModelViewSet

from accounts.models import Team, UserTeamRequest, User, UserProfile
from accounts.forms import CustomRegistrationForm, UserProfileForm, UserTeamRequestCreateForm, TeamCreateForm
from accounts.serializers import UserTeamRequestListSerializer
from accounts.utils import user_without_team
from challenges.models import Challenge
from challenges.models import Category


def index(request):
    return render(request, 'accounts/teams.html', {
        'teams': Team.objects.all(),
        'teams_count': Team.objects.count(),
    })


class CustomRegistrationView(RegistrationView):
    form_class = CustomRegistrationForm
    profile_form = None
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.profile_form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid() and self.profile_form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def register(self, form):
        # new_user = super(CustomRegistrationView, self).register(form)
        new_user = form.save()
        profile = self.profile_form.save(commit=False)
        profile.user = new_user
        profile.save()
        return new_user

    def get_context_data(self, **kwargs):
        kwargs['profile_form'] = self.profile_form or UserProfileForm()
        return super(CustomRegistrationView, self).get_context_data(**kwargs)


def team_detail(request, pk=None):
    user = request.user
    team = user.profile.team if pk is None else Team.objects.get(pk=pk)

    categories = Category.objects.all()
    categories_num_done_user = [
        c.challenges.filter(solved_by=user.profile).distinct().count()
        for c in categories
    ]
    categories_num_done_team = [
        c.challenges.filter(solved_by__team=team).distinct().count()
        for c in categories
    ]

    parameters = {
        'team': team,
        'total_points_count': Challenge.objects.total_points(),
        'time_points': json.dumps(team.score_over_time),
        'category_solved': team.percentage_solved_by_category,
        'last_team_solutions': team.challengesolved_set.order_by('-datetime').all(),

        'categories_names': json.dumps([c.name for c in categories]),
        'categories_num_done_user': categories_num_done_user,
        'categories_num_done_team': categories_num_done_team,
        'categories_num_total': [c.challenges.count() for c in categories],
    }

    return render(request, 'accounts/team.html', parameters)


def no_team_view(request, create_form=TeamCreateForm(), join_form=UserTeamRequestCreateForm()):
    # TODO: use permissions
    if not user_without_team(request.user):
        return redirect('index')

    pending_request = request.user.userteamrequest_set.pending().first()
    if pending_request:
        return render(request, 'accounts/pending_request.html', dict(join_request=pending_request))

    return render(request, 'accounts/no_team.html', dict(
        team_create_form=create_form,
        team_join_form=join_form,
        teams=Team.objects.all(),
        join_request_rejected=request.user.userteamrequest_set.rejected().exists()
    ))


class NoTeamPostView(CreateView):
    success_url = '/'
    form_name = None

    # TODO: use permissions
    def get(self, *args, **kwargs):
        return redirect('no_team')

    def form_invalid(self, form):
        return no_team_view(self.request, **{self.form_name: form})


class TeamCreateView(NoTeamPostView):
    form_class = TeamCreateForm
    success_url = reverse_lazy('index')
    form_name = 'create_form'

    def form_valid(self, form):
        team=form.save(commit=False)
        team.created_by=self.request.user
        team.save()
        team.created_by.profile.team = team
        team.created_by.profile.save()
        return super(TeamCreateView, self).form_valid(form)


class UserTeamRequestCreate(NoTeamPostView):
    form_class = UserTeamRequestCreateForm
    form_name = 'join_form'

    def get_form(self):
        return UserTeamRequestCreateForm(data=dict(
            user=self.request.user.pk,
            team=self.request.POST.get('team')))


class TeamAdminView(TemplateView):
    template_name = 'accounts/team_admin.html'

    # TODO: use permissions
    def get(self, request, *args, **kwargs):
        if not self.request.user.created_team.first():
            return redirect('index')
        return super(TeamAdminView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        return dict(
            join_requests=self.request.user.created_team.first().userteamrequest_set.order_by('-datetime')
        )


def user_detail(request, pk=None):
    user = request.user if pk is None else get_user_model().objects.get(pk=pk)

    solved = user.profile.percentage_solved_by_category
    categories_names = list(solved.keys())
    categories_num_done_user = [solved[c] for c in categories_names]

    parameters = {
        'categories_names': json.dumps(categories_names),
        'categories_num_done_user': categories_num_done_user,
        'user_detail_page': user,
        'time_points': json.dumps(user.profile.score_over_time),
    }
    return render(request, 'accounts/user.html', parameters)


class UserProfileUpdateView(UpdateView):
    model = UserProfile
    fields = ['image', 'job', 'website', 'skills']
    success_url = reverse_lazy('user')

    def get_object(self, queryset=None):
        return self.request.user.profile



class UserTeamRequestDelete(DeleteView):
    model = UserTeamRequest
    success_url = reverse_lazy('no_team')

    # TODO: use permissions
    def dispatch(self, request, *args, **kwargs):
        r = self.get_object()
        if r.user != request.user and r.team.created_by != request.user:
            return HttpResponseForbidden()
        return super(UserTeamRequestDelete, self).dispatch(request, *args, **kwargs)


class UserTeamRequestManage(UpdateView):
    model = UserTeamRequest
    fields = ['status']
    success_url = reverse_lazy('team_admin')
    http_method_names = ['post']

    # TODO: use permissions
    def post(self, request, *args, **kwargs):
        r = self.get_object()
        if not r.team.created_by == request.user:
            return Response('You are not team admin', status=403)
        if r.status != 'P':
            return Response('Not yet pending', status=400)
        return super(UserTeamRequestManage, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        response = super(UserTeamRequestManage, self).form_valid(form)
        if self.object.status == 'A':
            self.object.user.profile.team = self.object.team
            self.object.user.profile.save()
        return response


class UserTeamRequestViewSet(ModelViewSet):
    serializer_class = UserTeamRequestListSerializer

    def get_queryset(self):
        return UserTeamRequest.objects.filter(team__created_by=self.request.user)


class UserRequestHTMLTable(TeamAdminView, TemplateView):
    template_name = 'accounts/team_admin_requests_list.html'

accounts/templates/django_registration/activate.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% block title %}{% if account %}{% trans "Activation complete" %}{% else %}{% trans "Activation problem" %}{% endif %}{% endblock %}
{% block content %}
{% url 'auth_login' as auth_login_url %}
{% if account %}
{% blocktrans %}
Thanks {{ account }}, activation complete!
You may now <a href='{{ auth_login_url }}'>login</a> using the username and password you set at registration.
{% endblocktrans %}
{% else %}
{% blocktrans %}Oops &ndash; it seems that your activation key is invalid.  Please check the url again.{% endblocktrans %}
{% endif %}
{% endblock %}

accounts/templates/django_registration/activation_complete.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% block title %}{% trans "Activation complete" %}{% endblock %}
{% block content %}
{% url 'auth_login' as auth_login_url %}
{% blocktrans %}
Thanks, activation complete!  You may now <a href='{{ auth_login_url }}'>login</a> using the username and password you set at registration.
{% endblocktrans %}
{% endblock %}

accounts/templates/django_registration/activation_email.html
{% load i18n %}
{% comment %}
This template is used for the html alternative of the activation email
if you use a django-registration backend that looks for it. e.g.
https://github.com/huseyinyilmaz/django-registration-extended-backend
{% endcomment %}
{% url 'registration_activate' activation_key as activation_key_url %}
{% blocktrans with sitename=site.name sitedomain=site.domain%}<body>
<h3>Account registration for {{ sitename }}</h3>
<p>
You (or someone pretending to be you) have asked to register an account at
<b>{{ sitename }}</b>.<br/>
If this wasn't you, please ignore this email and your address will be removed
from our records.
</p>
<p>
To activate this account, please click the following link within the next 
<b>{{ expiration_days }}</b> days:<br/>
<a href="http://{{ sitedomain }}{{ activation_key_url }}">http://{{ sitedomain }}{{  activation_key_url }}</a>
</p>
<p>
Sincerely,<br/>
{{ sitename }} Management
</p>
</body>
{% endblocktrans %}

accounts/templates/django_registration/logout.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% block title %}{% trans "Logged out" %}{% endblock %}
{% block content %}
{% trans "Successfully logged out!" %}
{% endblock %}

accounts/templates/django_registration/password_reset_form.html
{% extends "registration/registration_base.html" %} 
{% load i18n %} 
{% block title %}Security CTF | Reset Password{% endblock %}
{% load static %}
{% block content %}

<!-- page content -->
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
             <h2 class="main_color_text"><i class="fa fa-home"></i> <a class="main_color_text" href="{% url 'login' %}">LOGIN</a> > PASSWORD RESET</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li style="margin-left: 46px;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="bs-example" data-example-id="simple-jumbotron">
                <div class="jumbotron" style="background-color:#333;">
                  <h3 style="color:#fff;text-align:center;margin-top:-25px;">Security Capture the Flag Platform.</h3><br>
				                   <h3 style="text-align:center;margin-bottom:-20px;"><img style="width:8%;" src="{% static 'sctf/images/top_big_blue.png' %}" alt=""></h3><br>
                  <h1 style="text-align:center;"><span class="main_color_text">What abaut Post-it?</span></h1>
				  <h3 style="color:#fff;text-align:center;margin-bottom:-20px;"></i> I bet you don't even remember what you ate at lunch yesterday
</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2 class="main_color_text"><i class="fa fa-info-circle"></i> PLEASE INSERT YOUR REGISTRATION EMAIL <small>required fields are identified by <span style="color:#E74C3C;">*</span></small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li style="margin-left: 46px;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<br>
						<form method="post" action="" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Email: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="email" required="required" id="id_email" type="email">
								</div>
							</div>
							{% if form.errors %}
							{{ form.errors }}
							<ul id="parsley-id-5" class="parsley-errors-list filled">
								<li class="parsley-required">{% blocktrans %}Forgot your password? Enter your email in the form below and we'll send you instructions for creating
									a new one.{% endblocktrans %}</li>
							</ul>
							{% endif %}
							<div class="form-group">
							</div>
							<div class="ln_solid"></div>
							<div style="float:left;">
								<i class="fa fa-user blue"></i> <a href="{% url 'login' %}">
									{% blocktrans %}Already an account, Log-In?{% endblocktrans %}
								</a>
							</div>
							<div class="form-group">
								<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
									<button class="btn btn-primary" type="reset">Cancel</button>
									<button type='submit' value="{% trans " Reset password "  %}" class="btn btn-success">Submit</button>
									<input type="hidden" name="next" value="{{ next }}" />
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /page content -->
{% endblock %}

accounts/templates/django_registration/registration_complete.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% block title %}{% trans "Activation email sent" %}{% endblock %}
{% block content %}
{% blocktrans %}An activation email has been sent.
Please check your email and click on the link to activate your account.{% endblocktrans %}
{% endblock %}

accounts/templates/django_registration/registration_form.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% block title %}Security CTF | Register{% endblock %}
{% load static %} 
{% block content %}

<!-- page content -->
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
             <h2 class="main_color_text"><i class="fa fa-home"></i> <a class="main_color_text" href="{% url 'login' %}">LOGIN</a> > REGISTRATION</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li style="margin-left: 46px;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="bs-example" data-example-id="simple-jumbotron">
                <div class="jumbotron" style="background-color:#333;">
                  <h3 style="color:#fff;text-align:center;margin-top:-25px;">Security Capture the Flag Platform.</h3><br>
				  <h3 style="text-align:center;margin-bottom:-20px;"><img style="width:8%;" src="{% static 'sctf/images/top_big_blue.png' %}" alt=""></h3><br>
                  <h1 style="text-align:center;"><span class="main_color_text">So You wanna register to CTF, eh?</span></h1>
				  <h3 style="color:#fff;text-align:center;margin-bottom:-20px;">Are You in Try Harder mode?</h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2 class="main_color_text"><i class="fa fa-info-circle"></i> PLEASE INSERT YOUR DATA <small>required fields are identified by<span style="color:#E74C3C;">*</span></small></h2>
						<ul class="nav navbar-right panel_toolbox">
							<li style="margin-left: 46px;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<br>
						<form enctype="multipart/form-data" method="post" action='' id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">{% csrf_token %}
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="username">{% trans form.username.label_tag %} <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="username" autofocus="" id="id_username" maxlength="254"
									    type="text" required="required">
									<div class="clearfix"></div>
									<span class="helptext">
										<ul>
											<li>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</li>
										</ul>
									</span>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="email" id="id_email" type="email" required="required">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="website">Website:</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="website" id="website" type="text">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first_name">First Name: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="first_name" id="id_first_name" type="text" required="required">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name">Last Name: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="last_name" id="id_last_name" type="text" required="required">
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12">Nationality: <span style="color:#E74C3C;" class="required">*</span></label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<select name="country" class="select2_group form-control" required="required">
									  {% for value, name in profile_form.fields.country.choices %}
										<option value="{{value}}">{{name}}</option>
									  {% endfor %}
								  </select>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last_name">Gender: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<p>
										<p class="helptext">
											Male: <input type="radio" class="flat" name="gender" id="genderM" value="M" required="required" /> Female: 
											<input type="radio" class="flat" name="gender" id="genderF" value="F" required="required" />
										</p>
									</p>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="image">Image:</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="file" id="image" name="image"/>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="job">Job Title: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="text" name="job" id="job" type="text" required="required">
								</div>
							</div>
							<div class="control-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="skills">Main Skills:</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input id="tags_1" type="text" name="skills" class="tags form-control" value="" />
									<div class="clearfix"></div>
									<span class="helptext">
										<ul>
											<li>Write skill and press Enter to add.</li>
										</ul>
									</span>
									<!--<div id="suggestions-container" style="position: relative; float: left; width: 250px; margin: 10px;"></div>-->
								</div>
							</div>
							<div class="clearfix"></div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">Password: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="password" name="password1" id="id_password1" type="password" required="required">
									<div class="clearfix"></div>
									<span class="helptext">
										<ul>
											<li>Your password can't be too similar to your other personal information.</li>
											<li>Your password must contain at least 8 characters.</li>
											<li>Your password can't be a commonly used password.</li>
											<li>Your password can't be entirely numeric.</li>
										</ul>
									</span>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Password Confirmation: <span style="color:#E74C3C;" class="required">*</span>
								</label>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<input class="form-control col-md-7 col-xs-12" type="password" name="password2" id="id_password2" type="password" required="required">
									<div class="clearfix"></div>
									<span class="helptext">
										<ul>
											<li>Enter the same password as before, for verification.</li>
										</ul>
									</span>
								</div>
							</div>
							{% if form.errors %}
							<ul id="parsley-id-5" class="parsley-errors-list filled">
								<li class="parsley-required">{% blocktrans %}Your data seems to be incorrect. Please respect the constraints.{% endblocktrans %}</li>
							</ul>
							{{ form.errors }}
							<!-- Dopo il test lato server ripristinare val lato client required="required" su ogni input -->
							{% endif %} {% if profile_form.errors %} {{ profile_form.errors }} {% endif %}
							<div class="form-group">
							</div>
							<div class="ln_solid"></div>
							<div style="float:left;">
								<i class="fa fa-user blue"></i> <a href="{% url 'login' %}">
							{% blocktrans %}Already an account, Log-In?{% endblocktrans %}
								</a>
							</div>
							<div class="form-group">
								<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
									<button class="btn btn-primary" type="reset">Cancel</button>
									<button type="submit" value="{% trans " Send activation email " %}" class="btn btn-success">Send Activation Mail</button>
									<input type="hidden" name="next" value="{{next}}" />
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /page content -->
{% endblock %} {% block extra_js %}

<script>
	$(document).ready(function () {
		init_TagsInput();
	});

	function init_TagsInput() {
		if (typeof $.fn.tagsInput !== 'undefined') {
			$('#tags_1').tagsInput({
				width: 'auto'
			});
		}
	};
</script>
{% endblock %}